/**
 * Replication Benchmarker
 * https://github.com/score-team/replication-benchmarker/
 * Copyright (C) 2011 INRIA / LORIA / SCORE Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jbenchmarker.core;

import crdt.CRDT;
import crdt.CRDTMessage;
import crdt.PreconditionException;
import crdt.simulator.IncorrectTraceException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Squeleton of mergeAlgorithm
 * @author urso
 */
public abstract class MergeAlgorithm extends CRDT<String> implements Serializable{

    private static final boolean DEBUG = false;
    
    // Supported Document
    final private Document doc;
       
    final private List<String> states  = new ArrayList<String>(1);  
    
    
    /*
     * Constructor
     */
    /**
     * 
     * @param doc Document of this merge algorithm
     * @param siteId SiteID or replicat number
     */
    public MergeAlgorithm(Document doc, int siteId) {
        this.doc = doc;
        this.setReplicaNumber(siteId);
    }

    public MergeAlgorithm(Document doc) {
        this.doc = doc;
    }

    /**
     * Integrate remote message from another replicas
     * To be define by the concrete merge algorithm
     * @param message from another replicas
     * @throws IncorrectTraceException 
     */
    protected abstract void integrateRemote(SequenceMessage message) throws IncorrectTraceException;
    
    /**
     * Integreate local modification of the document.
     * To be define by the concrete merge algorithm
     * @param opt local modification
     * @return Messages generated by replication algorithm will sent to another replicas
     * @throws IncorrectTraceException  
     */
    protected abstract List<SequenceMessage> generateLocal(SequenceOperation opt) throws IncorrectTraceException;
        
    /**
     * 
     * @return the document
     */
    public Document getDoc() {
        return doc;
    }

    /**
     * This the mergeAlgorithm return in initial state
     */
    public void reset() {
    }

    /**
     * This function to stay compatible with causal dispatcher 
     * localmodification is performed and a sequence message is transformed to CRDTMessage.
     * @param op local operation
     * @return CRDT message will be sent to another
     * @throws PreconditionException
     */
    @Override
    public CRDTMessage applyLocal(jbenchmarker.core.Operation op) throws PreconditionException {
        List<SequenceMessage> l = generateLocal((SequenceOperation) op);
        
        // FIXME: when l is an empty list, a NullPointerException is thrown...
        
        SequenceMessage m = null;
        for (SequenceMessage n : l) {
            if (m == null) { 
                m = n;
            } else {
                m.concat(n);
            }
        }        
        if (DEBUG) states.add(doc.view());

        return m;
    }

    /**
     * integrate remote operations.
     * @param msg message generated by another replicas
     */
    @Override
    public void applyRemote(CRDTMessage msg) {
        try {
            SequenceMessage s = (SequenceMessage) msg;
            integrateRemote(s);    
            for (Object m : s.getMsgs()) {
                integrateRemote((SequenceMessage) m);
            }
        } catch (IncorrectTraceException ex) {
            throw new IllegalStateException(ex);
        }
        
        if (DEBUG) states.add(doc.view());
    }

    /**
     * return document 
     * @return
     */
    @Override
    public String lookup() {
        return doc.view();
    }
}
